title: ðŸš€ðŸ‘¨ðŸ¼â€ðŸ’»ðŸ›¸ Shankar's Page
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal page, which is under construction. 
  I will be posting about my projects, thoughts, and other things that I find interesting. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog
locale: en_US
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ShankarHaran3
github_username:  devshank3
linkedin_username: shankar-hariharan-k

author:
  name: Shankar Hariharan K

# Build settings
theme: minima

minima:
  social_links:
    github: devshank3