title: ðŸ‘¨ðŸ¼â€ðŸ’»ðŸ“ Shankar's Page
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal page, which is under construction. 
  I will be posting about my projects, thoughts, and other things that I find interesting. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog
locale: en_US
url: "https://devshank3.github.io/"


author:
  name: Shankar Hariharan K


remote_theme: jekyll/minima

header_pages:
  - about.md
  - contact.md
  - tags.md

page_excerpts:
  enabled: true
  
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/devshank3/" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/shankar-hariharan-k"}
    - { platform: twitter,        user_url: "https://twitter.com/ShankarHaran3" }
    - { platform: x,              user_url: "https://x.com/ShankarHaran3" }