title: ðŸ‘¨ðŸ¼â€ðŸ’»ðŸ“ Shankar's Page
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal page, which is under construction. 
  I will be posting about my projects, thoughts, and other things that I find interesting. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog
locale: en_US
url: "https://devshank3.github.io/"
twitter_username: ShankarHaran3
github_username:  devshank3
linkedin_username: shankar-hariharan-k

author:
  name: Shankar Hariharan K


remote_theme: jekyll/minima

header_pages:
  - about.md
  - tags.md
  
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/devshank3/" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/shankar-hariharan-k"}